<?php

namespace Pletnev\ProjectManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaskPriorityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskPriorityRepository extends EntityRepository
{
}
